version: "3"

services:
  vpn:
    image: dperson/openvpn-client
    cap_add:
      - net_admin
    environment:
      TZ: "EST5EDT"
    networks:
      - download
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - 51413:51413
      - 51413:51413/udp
    tmpfs:
      - /run
      - /tmp
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    volumes:
      - ./config:/vpn

  bit:
    image: dperson/transmission
    depends_on:
      - vpn
    environment:
      TZ: "EST5EDT"
    restart: unless-stopped
    stdin_open: true
    tty: true
    network_mode: service:vpn
    volumes:
      - ./downloads:/downloads

  web:
    image: dperson/nginx
    depends_on:
      - vpn
    environment:
      TZ: "EST5EDT"
    links:
      - vpn:bit
    networks:
      - download
    ports:
      - "80:80"
      - "443:443"
    read_only: true
    tmpfs:
      - /run
      - /tmp
      - /var/cache/nginx
    restart: unless-stopped
    stdin_open: true
    tty: true
    command: -w "http://bit:9091/transmission;/transmission"

networks:
  download:
